### PR TITLE
Simplify `trainable`, `functor` and `Parallel`

### LINKED ISSUE #1685: `Parallel` edge-cases
First, about vararg vs single-argument. I think this is the documented behaviour, using `zip`, but how surprising is this? Is its early stopping a feature or a footgun?
```julia
julia> Parallel(hcat, x->x.+1, x->x.+2, x->x.+3)([0])  # one argument for all mode
1×3 Matrix{Int64}:
 1  2  3

julia> Parallel(hcat, x->x.+1, x->x.+2, x->x.+3)([0], [0])  # vararg => zip mode, zip ignores 3rd layer 
1×2 Matrix{Int64}:
 1  2

julia> Parallel(hcat, x->x.+1, x->x.+2, x->x.+3)([0], [0], [0], [1000])  # zip ignores 4th argument
1×3 Matrix{Int64}:
 1  2  3
```

Second, from the docs it's not very clear whether "reducing the output with `connection`" means pairwise, or vararg. In fact it means pairwise, which is the same (if slightly less efficient) for `+`, `vcat`, etc.
```julia
julia> myplus(xs...) = begin println("+ ", length(xs)); +(xs...) end;

julia> Parallel(myplus, identity, identity, identity)([1]);
+ 2
+ 2

julia> Parallel(myplus, identity, identity, identity)([1], [1], [1]);
+ 2
+ 2
```

Third, it currently allows the construction of a layer with no sub-layers, but this cannot be called. Is this desirable to allow some automatic generation not not to produce errors in a trivial case, even if it cannot be called? Would it be better to error on construction? Or should calling this be given some meaning --- if `connection` is vararg, then possibly `Parallel(myplus)([1]) == +([1])`?
```julia
julia> Parallel(myplus)
Parallel(myplus, )

julia> ans([1])
ERROR: ArgumentError: reducing over an empty collection is not allowed
```
In fact, even for one sub-layer there are surprises. Probably this should run, but should it call the `connection` with one argument, or not? (At present, not).
```julia
julia> Parallel(myplus, identity)([1]);
ERROR: MethodError: no method matching iterate(::typeof(identity))

julia> Parallel(myplus, (identity,))([1])
1-element Vector{Int64}:
 1

julia> Parallel(myplus, Dense(1,1));  # constructor runs...

julia> Flux.trainable(Parallel(myplus, Dense(1,1)))  # ... but this causes `show` to fail
ERROR: MethodError: no method matching iterate(::Dense{typeof(identity), Matrix{Float32}, Vector{Float32}})

julia> Parallel(myplus, Dense(1,1))([1])  # same error on calling
ERROR: MethodError: no method matching iterate(::Dense
```

(Split off from discussion in #1681, which is really orthogonal.)

### LINKED ISSUE #1857: `Chain` forgets names under `fmap`
From https://github.com/FluxML/Optimisers.jl/pull/49#issuecomment-1028165105, this isn't great:

```julia
julia> fmap(identity, Chain(x=sin, y=cos))
Chain(sin, cos)
```
The culprit is this `functor` method, which could be extended to deal with this. 

https://github.com/FluxML/Flux.jl/blob/fe803a1a706eb7ecbbf46f7c7e6c20b01847146d/src/layers/basic.jl#L44

Or we could delete it, and let Chain be more like Parallel:

```julia
julia> Flux.functor(Chain(x=sin, y=cos))
((x = sin, y = cos), Flux.var"#154#155"())

julia> Flux.functor(Parallel(vcat, (x=sin, y=cos)))
((connection = vcat, layers = (x = sin, y = cos)), Flux.var"#178#179"())
```

Then we would want delete the inner constructor for Chain, so that it accepts a tuple, `Chain((sin, cos)) == Chain(sin, cos)`. That would line up with https://github.com/FluxML/Flux.jl/pull/1809 allowing `Chain([sin, cos])` as a type-unstable variant.

### PR DESCRIPTION
**Pull request by mcabbott**
This does a few things to do with Functors / Optimisers:
* Changes all uses of `trainable` to return a NamedTuple, which is what Optimisers now wants.
* Removes the use of `trainable` on Parallel, since all fields are trainable, the layers are just one wrapper deeper.
* Removes the inner constructor from `Chain`, so that it can simply be `@functor Chain`. Fixes #1857 . 
* Likewise removes the inner constructor from `Maxout`.
* Adjusts the `show` code not to use `trainable`. This is most of why all these changes are in one PR.

The downside of no longer hiding the Tuple inside Chain from Functors.jl is that `fcollect` and hence `Flux.modules` will see it. ~~This is why the tests fail. I'm not too sure what this is for, and whether this matters.~~ Tests updated to allow this.

The PR also changes Parallel to call its `connection` exactly once, always. And to allow, with N layers, either 1 input or exactly N inputs. It used to zip, but (IMO) allowing N-1 inputs just seems like a bug magnet. These can be separated if anyone feels strongly. Fixes #1685, closes #1698.

### CODE REVIEW

**Comment by darsnack** [comment]
`modules` provides a flattened iterator for 1-level above the leaves. So it gives you the ordered list of nodes seen during the traversal. It's use case is regularizers like
```julia
sum(regularize(l) for l in modules(model))
```
where `regularize` can dispatch by layer type.

So I think for a breaking change, we can put a note in the docs/NEWS and update the tests, but this will not affect the expected use case.

**Comment by mcabbott** [comment]
Ok. Possibly it should filter out all types owned by Base? With `Parallel` you get a tuple of layers, before this PR, which you don't get with `Chain`
```
julia> Flux.modules(Chain(Parallel(+, Dense(2,2,sin), Dense(2,2,cos)), Dense(2,2,tan)))
6-element Vector{Any}:
 Chain(Parallel(+, Dense(2, 2, sin), Dense(2, 2, cos)), Dense(2, 2, tan))  # 18 parameters
 Parallel(+, Dense(2, 2, sin), Dense(2, 2, cos))  # 12 parameters
 (Dense(2, 2, sin), Dense(2, 2, cos))
 Dense(2, 2, sin)    # 6 parameters
 Dense(2, 2, cos)    # 6 parameters
 Dense(2, 2, tan)    # 6 parameters
```

File: test/runtests.jl [hunk 1]
```diff
@@ -8,55 +8,58 @@ using CUDA
 
 Random.seed!(0)
 
-@testset "Utils" begin
-  include("utils.jl")
-end
+@testset verbose=true "Flux.jl" begin
```
Comment (mcabbott) [inline test/runtests.jl:11]: This PR also adds an overall testset, so that all tests are run even if one fails near the start.

**Comment by darsnack** [comment]
> Or perhaps that's just more confusing and staying closer to the literal structure is better.

I think so. And ultimately, only the last three elements above will matter for the expected use case.

File: src/layers/normalise.jl [hunk 2]
```diff
@@ -82,8 +82,7 @@ function Dropout(p; dims=:, rng = rng_from_array())
 end
 
 @functor Dropout
```
Comment (ToucheSir) [inline src/layers/normalise.jl:84]:
```suggestion
@functor Dropout (rng,)
```
While we're at it?

File: src/layers/basic.jl [hunk 3]
```diff
@@ -460,25 +455,31 @@ function Parallel(connection; kw...)
...
+    throw(ArgumentError("Parallel with $nl sub-layers can take one input or $nl inputs, but got $nx inputs"))
+  end
+  m.connection(map(|>, xs, Tuple(m.layers))...)
+end
 
 Base.getindex(m::Parallel, i) = m.layers[i]
-Base.getindex(m::Parallel, i::AbstractVector) = Parallel(m.connection, m.layers[i]...)
+Base.getindex(m::Parallel, i::AbstractVector) = Parallel(m.connection, m.layers[i])
+Base.getindex(m::Parallel{<:Any, <:NamedTuple}, i::AbstractVector) =
+  Parallel(m.connection, NamedTuple{Base.keys(m)[i]}(Tuple(m.layers)[i]))
```
Comment (ToucheSir) [inline src/layers/basic.jl:479]:
```suggestion
  Parallel(m.connection, NamedTuple{Base.keys(m)[i]}(m.layers))
```
Does the same thing, I believe. Alas neither is type stable.

File: src/layers/basic.jl [hunk 4]
```diff
@@ -28,29 +28,30 @@ julia> m2(x) == (m2[:dec] ∘ m2[:enc])(x)
...
 applychain(fs::Tuple, x) = applychain(tail(fs), first(fs)(x))
 
 (c::Chain)(x) = applychain(Tuple(c.layers), x)
 
-Base.getindex(c::Chain, i::AbstractArray) = Chain(c.layers[i]...)
-Base.getindex(c::Chain{<:NamedTuple}, i::AbstractArray) = 
-  Chain(; NamedTuple{Base.keys(c)[i]}(Tuple(c.layers)[i])...)
+Base.getindex(c::Chain, i::AbstractArray) = Chain(c.layers[i])
+Base.getindex(c::Chain{<:NamedTuple}, i::AbstractArray) =
+  Chain(NamedTuple{Base.keys(c)[i]}(Tuple(c.layers)[i]))
```
Comment (ToucheSir) [inline src/layers/basic.jl:54]:
```suggestion
  Chain(NamedTuple{Base.keys(c)[i]}(c.layers))
```
Same as `Parallel`.

File: src/layers/basic.jl (hunk 3 above)
Comment (mcabbott) [reply src/layers/basic.jl:479]: TIL:
```
julia> NamedTuple{(:a, :c)}((a=1, b=2, c=3))
(a = 1, c = 3)
```

File: src/layers/normalise.jl (hunk 2 above)
Comment (mcabbott) [reply src/layers/normalise.jl:84]: I see, to protect `p` from training, but still move RNG to the GPU.

Are there any downsides to doing it this way, rather than `trainable(d:: Dropout) = (;)`?

Comment (ToucheSir) [reply src/layers/normalise.jl:84]: They're complementary changes. I don't think it's super necessary to selectively functor for Dropout since it doesn't have any non-trainable array params, but at some point it would be good to clean house.

**Comment by mcabbott** [comment]
Good to go?

**Review by ToucheSir — APPROVED** [review]
