### PR TITLE
fix cpu(x) for immutable arrays

### LINKED ISSUE #2116: `cpu(x)` errors for `x isa CuArray{<:CartesianIndex}`
### Package Version

Flux v0.13.7

### Julia Version

1.8.2

### OS / Environment

Ubuntu 20.04

### Describe the bug

I can copy an `Array` of `CartesianIndex`s to the GPU using Flux's convenience function `gpu()`, but not back to the CPU again using `cpu()`. The `Array` constructor works, though. See the MWE below.

### Steps to Reproduce

```
julia> using Flux

julia> x_cpu = [CartesianIndex(1)]
1-element Vector{CartesianIndex{1}}:
 CartesianIndex(1,)

julia> x_gpu = gpu(x_cpu)
1-element CUDA.CuArray{CartesianIndex{1}, 1, CUDA.Mem.DeviceBuffer}:
 CartesianIndex(1,)

julia> Array(x_gpu)    #Works
1-element Vector{CartesianIndex{1}}:
 CartesianIndex(1,)

julia> cpu(x_gpu)    #Does not work
ERROR: GPU broadcast resulted in non-concrete element type Any.
This probably means that the function you are broadcasting contains an error or type instability.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] copy
    @ ~/.julia/packages/GPUArrays/fqD8z/src/host/broadcast.jl:34 [inlined]
  [3] materialize(bc::Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{1}, Nothing, Functors.var"#16#17"{typeof(Functors.isleaf), typeof(Functors._default_walk), IdDict{Any, Any}, Functors.NoKeyword, Flux.var"#160#161"}, Tuple{CUDA.CuArray{CartesianIndex{1}, 1, CUDA.Mem.DeviceBuffer}}})
    @ Base.Broadcast ./broadcast.jl:860
  [4] map(::Function, ::CUDA.CuArray{CartesianIndex{1}, 1, CUDA.Mem.DeviceBuffer})
    @ GPUArrays ~/.julia/packages/GPUArrays/fqD8z/src/host/broadcast.jl:82
  [5] _default_walk
    @ ~/.julia/packages/Functors/V2McK/src/functor.jl:39 [inlined]
  [6] fmap(f::Flux.var"#160#161", x::CUDA.CuArray{CartesianIndex{1}, 1, CUDA.Mem.DeviceBuffer}; exclude::typeof(Functors.isleaf), walk::typeof(Functors._default_walk), cache::IdDict{Any, Any}, prune::Functors.NoKeyword)
    @ Functors ~/.julia/packages/Functors/V2McK/src/functor.jl:46
  [7] fmap
    @ ~/.julia/packages/Functors/V2McK/src/functor.jl:44 [inlined]
  [8] cpu(x::CUDA.CuArray{CartesianIndex{1}, 1, CUDA.Mem.DeviceBuffer})
    @ Flux ~/.julia/packages/Flux/nJ0IB/src/functor.jl:154
  [9] top-level scope
    @ REPL[4]:1
 [10] top-level scope
    @ ~/.julia/packages/CUDA/DfvRa/src/initialization.jl:52
```

### Expected Results

Well, I expected to get `x_cpu` back; `x_cpu == cpu(gpu(x_cpu))`.

### Observed Results

`cpu(gpu(x_cpu))` errors for `x_cpu isa Array{<:CartesianIndex}` .

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by CarloLucibello**
Fix #2116 and more generally fix the conversion from  `CuArray{T}`  where `T` is immutable. 

Are there any counterindications for doing this?

### CODE REVIEW

File: test/cuda/cuda.jl [hunk 1]
```diff
@@ -165,4 +165,16 @@ end
...
+  #Issue #2116  
+  struct A2116
+    x::Int
+    y::Int
+  end
+  x = [A2116(1,1), A2116(2,2)]
+  xgpu = gpu(x) 
+  @test xgpu isa CuVector{A2116}
+  @test cpu(xgpu) isa Vector{A2116} 
+  @test cpu(gpu([CartesianIndex(1)])) isa Vector
```
Comment (DhairyaLGandhi) [inline test/cuda/cuda.jl:179]:
```suggestion
  @test cpu(gpu([CartesianIndex(1)])) isa Vector{CartesianIndex}
```

File: test/cuda/cuda.jl [hunk 2]
```diff
@@ -165,4 +165,16 @@ end
   @test gpu(g2) isa CuArray
   @test gpu(g2) ≈ cu(Vector(g2))
   @test parent(gpu(g3)) isa CuArray
+
```
Comment (ToucheSir) [inline test/cuda/cuda.jl:168]: Adding this here because I can't comment on lines not covered by the diff. https://github.com/FluxML/Flux.jl/blob/1914f3814a01577d9ec651369366fe734c5c1e91/test/cuda/cuda.jl#L117 is also failing.
```julia-repl
julia> gradient(x -> sum(abs, cpu(x)), a')[1]
4×4 adjoint(adjoint(::Matrix{Float32})) with eltype Float32:
  1.0  -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0   1.0
  1.0  -1.0   1.0  -1.0
 -1.0   1.0   1.0   1.0
```
Whereas before it returned a `Matrix{Float32}`. I'm not sure where the double wrapping is coming from, maybe CRC?

**Review by ToucheSir — COMMENTED** [review]
Two real failures on Buildkite GPU CI:

File: test/cuda/cuda.jl (hunk 2 above)
Comment (CarloLucibello) [reply test/cuda/cuda.jl:168]: yeah I don't know where that comes from

Comment (CarloLucibello) [reply test/cuda/cuda.jl:168]: I didn't manage to understand the root cause, but I circumvented the issue with a bunch of rrules for `adapt`. 
It's not ideal but at least we get to fix #2116

File: src/functor.jl [hunk 3]
```diff
@@ -121,14 +121,28 @@ adapt_storage(to::FluxCPUAdaptor, x::AbstractSparseArray) = x
...
 function ChainRulesCore.rrule(::typeof(Adapt.adapt_storage), to::FluxCPUAdaptor, x::CUDA.AbstractGPUArray)
-  adapt_storage(to, x), dx -> (NoTangent(), NoTangent(), adapt_storage(FluxCUDAAdaptor(), unthunk(dx)),)
+  adapt_storage(to, x), dx -> (NoTangent(), NoTangent(), adapt_storage(FluxCUDAAdaptor(), unthunk(dx)))
 end
 
+ChainRulesCore.rrule(::typeof(adapt), a::FluxCPUAdaptor, x::AnyCuArray) =
+  adapt(a, x), Δ -> (NoTangent(), NoTangent(), adapt(FluxCUDAAdaptor(), unthunk(Δ)))
+
+ChainRulesCore.rrule(::typeof(adapt), a::FluxCPUAdaptor, x::AbstractArray) =
+  adapt(a, x), Δ -> (NoTangent(), NoTangent(), unthunk(Δ))
```
Comment (CarloLucibello) [inline src/functor.jl:137]:
```suggestion
  adapt(a, x), Δ -> (NoTangent(), NoTangent(), Δ)
```

File: src/functor.jl [hunk 4]
```diff
@@ -121,14 +121,28 @@ adapt_storage(to::FluxCPUAdaptor, x::AbstractSparseArray) = x
...
+
+ChainRulesCore.rrule(::typeof(adapt), a::FluxCUDAAdaptor, x::AnyCuArray) =
+  adapt(a, x), Δ -> (NoTangent(), NoTangent(), unthunk(Δ))
```
Comment (CarloLucibello) [inline src/functor.jl:140]:
```suggestion
  adapt(a, x), Δ -> (NoTangent(), NoTangent(), Δ)
```

File: test/cuda/cuda.jl (hunk 2 above)
Comment (ToucheSir) [reply test/cuda/cuda.jl:168]: Seems reasonable and Adapt is a nicer level to work at than our own functions anyhow. Do you mind just leaving a comment before the block of rules noting that they're required to prevent this double-wrapping issue?

File: src/functor.jl [hunk 5]
```diff
@@ -121,14 +121,28 @@ adapt_storage(to::FluxCPUAdaptor, x::AbstractSparseArray) = x
...
-  Array(x), dx -> (NoTangent(), CUDA.cu(unthunk(dx)),)
+  Array(x), dx -> (NoTangent(), CUDA.cu(unthunk(dx)))
 end
 
 function ChainRulesCore.rrule(::typeof(Adapt.adapt_storage), to::FluxCPUAdaptor, x::CUDA.AbstractGPUArray)
-  adapt_storage(to, x), dx -> (NoTangent(), NoTangent(), adapt_storage(FluxCUDAAdaptor(), unthunk(dx)),)
+  adapt_storage(to, x), dx -> (NoTangent(), NoTangent(), adapt_storage(FluxCUDAAdaptor(), unthunk(dx)))
 end
 
+ChainRulesCore.rrule(::typeof(adapt), a::FluxCPUAdaptor, x::AnyCuArray) =
```
Comment (CarloLucibello) [inline src/functor.jl:133]:
```suggestion
# The following rrules for adapt are here to avoid double wrapping issues
# as seen in https://github.com/FluxML/Flux.jl/pull/2117#discussion_r1027321801

ChainRulesCore.rrule(::typeof(adapt), a::FluxCPUAdaptor, x::AnyCuArray) =
```

File: test/cuda/cuda.jl (hunk 2 above)
Comment (CarloLucibello) [reply test/cuda/cuda.jl:168]: done!

**Review by ToucheSir — APPROVED** [review]
