### PR TITLE
Fix #2086 re `@autosize`

### LINKED ISSUE #2086: `@autosize` does not work with semi-colon separated kwargs
### Package Version

master branch

### Julia Version

1.8.2

### OS / Environment

Software:

    System Software Overview:

      System Version: macOS 12.6 (21G115)
      Kernel Version: Darwin 21.6.0

Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Chip: Apple M1

### Describe the bug

The `@autosize` macro throws an error (which looks unrelated to `Flux`) if the keyword arguments are separated by a semi-colon. The macro works if I run the same code, but with the semi-colon removed.

### Steps to Reproduce

```julia
@autosize (3, 1) Chain(; c = Dense(_ => 2, sigmoid), b = BatchNorm(_, affine=false))
```

### Expected Results

I expected this to work like it does without the semi-colon -
```julia
julia> @autosize (3, 1) Chain(c = Dense(_ => 2, sigmoid), b = BatchNorm(_, affine=false))
Chain(
  c = Dense(3 => 2, σ),                 # 8 parameters
  b = BatchNorm(2, affine=false),
)
```

### Observed Results

```julia
ERROR: syntax: all-underscore identifier used as rvalue around /Users/saransh/Code/julia-dev/FluxML/Flux.jl/src/outputsize.jl:256
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
 [2] top-level scope
   @ ~/.julia/packages/CUDA/DfvRa/src/initialization.jl:52
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mcabbott**
Closes #2086

### CODE REVIEW

**Review by ToucheSir — APPROVED** [review]

File: test/outputsize.jl [hunk 1]
```diff
@@ -174,12 +174,20 @@ end
   
   m = @autosize (2, 3, 4, 5) Dense(_ => 10)  # goes by first dim, not 2nd-last
   @test randn(2, 3, 4, 5) |> m |> size == (10, 3, 4, 5)
-  
+
+  @test_broken begin  # outputsize fails on Embedding
+    m = @autosize (2, 3, 4, 5) Embedding(_ => 10)  # goes by first dim, not 2nd-last
+    @test randn(2, 3, 4, 5) |> m |> size == (10, 3, 4, 5)
+  end
```
Comment (mcabbott) [inline test/outputsize.jl:181]: This isn't right, BTW. 

Fixed in https://github.com/FluxML/Flux.jl/pull/2088/commits/179ac9bec6bb18944c1470c6cc54e226ae68afe1, in #2088
