### PR TITLE
Adjust docs & `Flux.@functor` for Functors.jl v0.5, plus misc. depwarns

### LINKED ISSUE #2533: `Flux.params` is broken
I know it's not really supported, but `params` is more broken than it should be (on master):
```julia
julia> Flux.params([2,3])
ERROR: UndefVarError: `IdSet` not defined

julia> @eval Flux using Base: IdSet

julia> Flux.params([2,3])
Params([[2, 3]])
```
It should probably print friendly upgrade instructions, `@warn "..." maxlog=1`. People calling this are probably struggling to update old code, and we should help them along.

### PR DESCRIPTION
**Pull request by mcabbott**
After https://github.com/FluxML/Functors.jl/pull/51 we should stop saying that you need either `@layer` or `@functor` for Flux to find your parameters.

This PR:
* defines a new macro `Flux.@functor` which prints a depwarn & then calls `@layer`
* ~~removes the code from `@layer` which printed other depwarns~~
* ~~removes the code from `@layer` which defines `functor`~~

Fixes #2533

WIP, more doc changes needed. 

### PR Checklist

- [ ] Tests are added
- [ ] Entry in NEWS.md
- [ ] Documentation, if applicable

### CODE REVIEW

**Comment by CarloLucibello** [comment]
Functors v0.5 is out

**Comment by CarloLucibello** [comment]
We can continue with this now that Functors v0.5 is in with #2525 
This is the last item in the v0.15 milestone

**Comment by CarloLucibello** [comment]
I subsumed most of this into #2528 in order to speed up the 0.15 release. 
I think only the `Flux.@functor` macro for smoothing the transition to `@layer` is left to be implemented.

**Comment by mcabbott** [comment]
It's not so much to add functionality, as to avoid this:
```
julia> Flux.@functor 1
ERROR: LoadError: UndefVarError: `@functor` not defined
```
IMO that's an extremely unfriendly upgrade path. It would be OK to just print an error message, but doing what you ask as well is pretty easy.

**Comment by mcabbott** [comment]
Yea, but better to prod people to update. Hence this PR.

File: src/deprecations.jl [hunk 1]
```diff
@@ -83,16 +83,48 @@ function params!(p::Zygote.Params, x, seen = IdSet())
...
+
+To collect all the parameter arrays for other purposes, use `Flux.trainables(model)`.
+"""
 function params(m...)
-  Base.depwarn("""
-  Flux.params(m...) is deprecated. Use `Flux.trainable(model)` for parameters' collection
-  and the explicit `gradient(m -> loss(m, x, y), model)` for gradient computation.
-  """, :params)
+  @warn """`Flux.params(m...)` is deprecated. Use `Flux.trainable(model)` for parameter collection,
+  and the explicit `gradient(m -> loss(m, x, y), model)` for gradient computation.""" maxlog=1
```
Comment (mcabbott) [inline src/deprecations.jl:99]: `Base.depwarn` is silent except in tests. IMO that's ideal if you are marking something deprecated *before* a breaking change, when the replacement is available.

However, my impression is that we really want people to change this, not to silently live with old code during 0.15. So I'd like something to be printed in interactive use.

Maybe the same goes for more of the depwarns in this file?

File: src/deprecations.jl [hunk 2]
```diff
@@ -119,9 +153,6 @@ end
 ### v0.16 deprecations ####################
 
 
-# Enable these when 0.16 is released, and delete const ClipGrad = Optimise.ClipValue etc: 
-# Base.@deprecate_binding Optimiser OptimiserChain
-# Base.@deprecate_binding ClipValue ClipGrad
```
Comment (mcabbott) [inline src/deprecations.jl:124]: These const definitions have already been deleted:
```
julia> Flux.ClipValue
ERROR: UndefVarError: `ClipValue` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[6]:1

julia> Flux.Optimiser
ERROR: UndefVarError: `Optimiser` not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:31
 [2] top-level scope
   @ REPL[7]:1
```

**Review by CarloLucibello — APPROVED** [review]
