### PR TITLE
misc stuff for v0.15 release

### LINKED ISSUE #2530: broken image in the quickstart
In the [quickstart](https://fluxml.ai/Flux.jl/dev/guide/models/quickstart/), After "Here's the loss during training:" the image is not displayed.

I don't know what is wrong with this line
https://github.com/FluxML/Flux.jl/blob/0a324f8f7eaeeb01f5c43c60322b6a2585b24ab4/docs/src/guide/models/quickstart.md?plain=1#L65

### PR DESCRIPTION
**Pull request by CarloLucibello**
- hopefully fix #2530 
- supersedes #2515 
- pins GPUArraysCore and GPUCompiler in tests in order to prevent inconsistencies in the environment (see https://github.com/JuliaGPU/CUDA.jl/issues/2564#issuecomment-2513505187)

TODO:
- [x] revisit gpu guide
- [x] reintegrate params docstring and show it in the docs
- [x] do a quick read of the whole documentation, see if something is odd
- [x] build the docs locally, see if we can make the compilation stricter 
- [ ] check if we can uncomment all the enzyme tests
- [ ] see why code coverage is low

### CODE REVIEW

File: src/deprecations.jl [hunk 1]
```diff
@@ -83,17 +83,6 @@ function params!(p::Zygote.Params, x, seen = IdSet())
...
-    params(model)
-
-Returns a `Zygote.Params` object containing all parameter arrays from the model.
-This is deprecated!
-
-This function was the cornerstone of how Flux used Zygote's implicit mode gradients,
-but since Flux 0.13 we use explicit mode `gradient(m -> loss(m, x, y), model)` instead.
-
-To collect all the parameter arrays for other purposes, use `Flux.trainables(model)`.
-"""
```
Comment (mcabbott) [inline src/deprecations.jl:96]: Why delete this?

Comment (CarloLucibello) [reply src/deprecations.jl:96]: because if we were a bit stricter in docs/make.jl Documenter would complain for any docstring not showing up in the documentation. And we have been deprecating `params` in various forms for a long time now, so I wouldn't want it in the docs.

**Review by mcabbott — COMMENTED** [review]
Thanks for pushing a bit, and especially for fighting CI.

I have some doc changes...
