### PR TITLE
multiplication of {Transpose, Adjoint} of Array and OneHotVector

### LINKED ISSUE #777: onehot ambiguous method
This looks like a bug:

```julia
julia> u = Flux.onehot(5, 1:10);
julia> m = randn(10,10);
julia> u' * m
ERROR: MethodError: *(::LinearAlgebra.Adjoint{Float64,Array{Float64,2}}, ::Flux.OneHotVector) is ambiguous. Candidates:
  *(A::AbstractArray{T,2} where T, b::Flux.OneHotVector) in Flux at /opt/julia-depot/packages/Flux/qXNjB/src/onehot.jl:12
  *(adjA::LinearAlgebra.Adjoint{#s623,#s622} where #s622<:AbstractArray{T,2} where #s623, x::AbstractArray{S,1}) where {T, S} in LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:103
Possible fix, define
  *(::LinearAlgebra.Adjoint{#s623,#s622} where #s622<:AbstractArray{T,2} where #s623, ::Flux.OneHotVector)
Stacktrace:
 [1] *(::LinearAlgebra.Adjoint{Bool,Flux.OneHotVector}, ::Array{Float64,2}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:122
 [2] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by gxyd**
Also fixes #777 . Tests have been added.

### CODE REVIEW

File: src/onehot.jl [hunk 1]
```diff
@@ -18,6 +18,20 @@ function Base.:*(A::AbstractMatrix, b::OneHotVector)
...
+    throw(DimensionMismatch("Adjoint matrix column must correspond with OneHotVector size"))
+  end
+  return A[:, b.ix]
+end
+
+function Base.:*(A::LinearAlgebra.Adjoint{T1,<:AbstractArray{T,1}}, b::OneHotVector) where {T1<:Number,T}
+  if size(A, 2) != b.of
+    throw(DimensionMismatch("Adjoint matrix column must correspond with OneHotVector size"))
+  end
+  return A[b.ix:b.ix]
```
Comment (mcabbott) [inline src/onehot.jl:32]: Possibly this should return a scalar, isn't it simulating this?
```
julia> rand(3)' * [0,1,0]
0.8769012011984989
```

File: src/onehot.jl [hunk 2]
```diff
@@ -18,6 +18,20 @@ function Base.:*(A::AbstractMatrix, b::OneHotVector)
   return A[:, b.ix]
 end
 
+function Base.:*(A::LinearAlgebra.Adjoint{T1,<:AbstractArray{T,2}}, b::OneHotVector) where {T1,T}
```
Comment (mcabbott) [inline src/onehot.jl:21]: Why isn't this case covered by `*(A::AbstractMatrix, b::OneHotVector)` above?

File: src/onehot.jl [hunk 3]
```diff
@@ -18,6 +18,20 @@ function Base.:*(A::AbstractMatrix, b::OneHotVector)
...
+  if size(A, 2) != b.of
+    throw(DimensionMismatch("Adjoint matrix column must correspond with OneHotVector size"))
+  end
+  return A[:, b.ix]
+end
+
+function Base.:*(A::LinearAlgebra.Adjoint{T1,<:AbstractArray{T,1}}, b::OneHotVector) where {T1<:Number,T}
+  if size(A, 2) != b.of
+    throw(DimensionMismatch("Adjoint matrix column must correspond with OneHotVector size"))
```
Comment (mcabbott) [inline src/onehot.jl:30]: Should this allow transpose too?
```suggestion
function Base.:*(A::AdjOrTransAbsVec, b::OneHotVector)
  if size(A, 2) != b.of
    throw(DimensionMismatch("length of row vector must match that of OneHotVector"))
```

File: src/onehot.jl (hunk 2 above)
Comment (gxyd) [reply src/onehot.jl:21]: As for the first argument in this case, the method defined in LinearAlgebra would be more specific
```jl
*(adjA::Adjoint{var"#s828",var"#s827"} where var"#s827"<:AbstractArray{T,2} where var"#s828", x::AbstractArray{S,1}) where {T, S} in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/matmul.jl:110
```

But for the second argument the method defined above i.e.
```jl
*(A::AbstractArray{T,2} where T, b::OneHotVector)
```
would be more specific. So that's why we need this method.

File: src/onehot.jl (hunk 1 above)
Comment (gxyd) [reply src/onehot.jl:32]: Agreed.

File: src/onehot.jl (hunk 3 above)
Comment (gxyd) [reply src/onehot.jl]: I think we'll need to have a separate methods for function `*`, for first argument as `Adjoint` or `Transpose` instead of single method as `Union{Adjoint, Transpose}`.

Ideally we would like to reduce such code-reduction, but I'm not sure if there any way to do that here?

File: test/onehot.jl [hunk 4]
```diff
@@ -27,9 +27,16 @@ end
...
   A = [1 3 5; 2 4 6; 3 6 9]
+  B = [1, 2, 3, 4, 5]
+  X = reshape(B, (5, 1))
   b1 = Flux.OneHotVector(1,3)
   b2 = Flux.OneHotVector(3,5)
 
   @test A*b1 == A[:,1]
+  @test b1' * A == (A'[:, b1.ix])'
+  @test A' * b1 == A'[:, b1.ix]
+  @test B' * b2 == B[b2.ix]
```
Comment (gxyd) [inline test/onehot.jl:38]: @mcabbott 

Should the ideal tests instead be something like:
```jl
@test B' * b2 == Array(B2) * Array(b2)
```

Same for other tests that we wrote in this PR. WDYT?

File: src/onehot.jl (hunk 2 above)
Comment (mcabbott) [reply src/onehot.jl:21]: Oh of course, sorry!

File: src/onehot.jl (hunk 3 above)
Comment (mcabbott) [reply src/onehot.jl]: Oh it is possible those are separated in LinearAlgebra's definitions. As of 1.5 there might be restrictions `T<:Number` too. 

Perhaps both the matrix and row-vector definitions can be inside a `for Wrap in [:Adjoint, :Transpose] @eval begin ...` loop?

File: test/onehot.jl (hunk 4 above)
Comment (mcabbott) [reply test/onehot.jl:38]: Yes, agreed. This is easier to read and tests the behaviour you ultimately care about.

File: src/onehot.jl (hunk 2 above)
Comment (mcabbott) [reply src/onehot.jl:21]: If not using or constraining T, clearer to write `AbstractMatrix` I think, not `AbstractArray{T,2}`

Comment (DhairyaLGandhi) [reply src/onehot.jl:21]: We don't need to qualify `Adjoint` do we

Comment (gxyd) [reply src/onehot.jl]: @DhairyaLGandhi  agreed.

@mcabbott when I do change `AbstractArray{T,2}` with `AbstractMatrix` I get the following error (which I wasn't expecting)

```jl
  MethodError: *(::Adjoint{Int64,Array{Int64,2}}, ::Flux.OneHotVector) is ambiguous. Candidates:
    *(adjA::Adjoint{var"#s828",var"#s827"} where var"#s827"<:AbstractArray{T,2} where var"#s828", x::AbstractArray{S,1}) where {T, S} in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/matmul.jl:110
    *(A::Adjoint{T1,var"#s129"} where var"#s129"<:(AbstractArray{T,2} where T), b::Flux.OneHotVector) where T1 in Flux at /Users/gaurav/.julia/dev/Flux/src/onehot.jl:23
  Possible fix, define
    *(::Adjoint{T1,var"#s129"} where var"#s129"<:AbstractArray{T,2}, ::Flux.OneHotVector) where {T1, T}
```

Similar error for `AbstractArray{T,1}` -> `AbstractVector`.

I didn't know if there is actually a difference between writing `where T` immediately vs writing `where T` outside parenthesis of function..

**Comment by gxyd** [comment]
@mcabbott this is ready for a review.

**Review by DhairyaLGandhi — DISMISSED** [review]

File: src/onehot.jl [hunk 5]
```diff
@@ -18,6 +18,24 @@ function Base.:*(A::AbstractMatrix, b::OneHotVector)
   return A[:, b.ix]
 end
 
+for math_op in [:Adjoint, :Transpose]
+  @eval begin
+    function Base.:*(A::$math_op{T1,<:AbstractArray{T,2}}, b::OneHotVector) where {T1,T}
+      if size(A, 2) != b.of
+        throw(DimensionMismatch("Adjoint matrix column must correspond with ONeHotVector size"))
```
Comment (DhairyaLGandhi) [inline src/onehot.jl:25]:
```suggestion
        throw(DimensionMismatch("Second element of Adjoint matrix size $(size(A)) must correspond with OneHotVector size $(size(b))"))
```

File: src/onehot.jl [hunk 6]
```diff
@@ -18,6 +18,24 @@ function Base.:*(A::AbstractMatrix, b::OneHotVector)
...
+      end
+      return A[:, b.ix]
+    end
+
+    function Base.:*(A::$math_op{T1,<:AbstractArray{T,1}}, b::OneHotVector) where {T1<:Number,T}
+      if size(A, 2) != b.of
+        throw(DimensionMismatch("length of row vector must match that of OneHotVector"))
```
Comment (DhairyaLGandhi) [inline src/onehot.jl:32]:
```suggestion
        throw(DimensionMismatch("Second element of Adjoint matrix size $(size(A)) must correspond with OneHotVector size $(size(b))"))
```

**Comment by DhairyaLGandhi** [comment]
Looks good, thanks!

File: src/onehot.jl [hunk 7]
```diff
@@ -18,6 +18,24 @@ function Base.:*(A::AbstractMatrix, b::OneHotVector)
   return A[:, b.ix]
 end
 
+for math_op in [:Adjoint, :Transpose]
+  @eval begin
+    function Base.:*(A::$math_op{T1,<:AbstractArray{T,2}}, b::OneHotVector) where {T1,T}
```
[the remark this answers is not in the document]
Comment (gxyd) [reply src/onehot.jl:23]: Sorry, didn't get you. You mean strong typing it as `{T1, <:AbstractArray{T,2}}`?

**Comment by CarloLucibello** [comment]
I think this is superseded by #1447. We should make sure that the tests added here get in there. Could merge this now, then #1447  should rebase and fix conflicts

**Comment by CarloLucibello** [comment]
Or we could wait for #1447 to be merged, then rebase this,  and fix #777 if it is not fixed already

**Comment by gxyd** [comment]
> Or we could wait for #1447 to be merged, then rebase this, and fix #777 if it is not fixed already

@CarloLucibello I think this solution sounds better, since that is a new way of implementation for the OneHot. I definitely don't mind if need be the code from this PR directly copied to the new OneHot implementation PR, so we directly fix it in that PR itself

**Comment by gxyd** [comment]
I'll keep this PR open? Since in case **wearen't** able to have new one-hot implementation ready for v0.12 , we can probably just think of this PR may be.

**Comment by DhairyaLGandhi** [comment]
Probably easier to merge this now since I'd like the tests in and rushing #1447 makes me uncomfortable since it makes strong decisions around using internal Julia functions and complicates its design

**Comment by darsnack** [comment]
Was this addressed by #1448 that superseded #1447? If so, we can close.

**Comment by ToucheSir** [comment]
Bump? The new OneHotArray has been in a few stable releases now.

**Comment by darsnack** [comment]
@gxyd I hope you don't mind, I just rebased your PR (all the code is same and your authorship is preserved). I think this PR is good to go once the checks pass.

**Comment by gxyd** [comment]
@darsnack I'm glad the code written could be of some help.

**Review by darsnack — APPROVED** [review]
Thanks @gxyd!
